name: A workflow for my Hello World file
on: push

jobs:
    build:
        name: hello world anction
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./action-a
              with:
                  MY_NAME: 'Mona'
